# Generated by Django 5.0.4 on 2025-02-11 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('service_type', models.CharField(choices=[('photo_videography', 'photo_videography'), ('event_planners', 'event_planners'), ('catering', 'catering'), ('bride_groom_service', 'bride_groom_service'), ('decoration', 'decoration'), ('transportation', 'transportation'), ('venue_planners', 'venue_planners')], default='event_planners', max_length=20)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
