# Generated by Django 5.0.4 on 2025-02-11 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookevent',
            name='our_service',
            field=models.CharField(choices=[('Transportation', 'Transportation'), ('Food', 'Food'), ('Photography', 'Photography')], max_length=50),
        ),
    ]
