# Generated by Django 5.0.4 on 2025-02-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_bookevent_our_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bridalgroomservicebooking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Rejected', 'Rejected'), ('Paid', 'Paid')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='cateringbooking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Rejected', 'Rejected'), ('Paid', 'Paid')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='decorationsbooking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Rejected', 'Rejected'), ('Paid', 'Paid')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='photographybooking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Rejected', 'Rejected'), ('Paid', 'Paid')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transportationbooking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Rejected', 'Rejected'), ('Paid', 'Paid')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='venuebooking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Rejected', 'Rejected'), ('Paid', 'Paid')], default='Pending', max_length=20),
        ),
    ]
