# Generated by Django 5.0.4 on 2025-02-11 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_bridalgroomservicebooking_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookevent',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Paid', 'Paid')], default='Pending', max_length=20),
        ),
    ]
